server:
  port: 10086
#  配置应用的名字
spring:
  application:
    name: eureka-server

    #配置 eureka相关的
eureka:
  client:
    register-with-eureka: false   #不把自己作为eureka服务注册
    fetch-registry: false  #不需要拉取服务列表
    service-url:      #配置服务的地址
      defaultZone: http://127.0.0.1:${server.port}/eureka