server:
  port: 8081
spring:
  application:
    name: user-service #将来的服务名称
  datasource:

    url: jdbc:mysql://localhost:3306/heima29?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: root
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10



mybatis:
  type-aliases-package: cn.itcast.userservice.pojo
  #配置 eureka的信息

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
