server:
  port: 8082
spring:
  application:
    name: user-service #将来的服务名称
  datasource:

    url: jdbc:mysql://localhost:3306/heima29?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: root
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10



mybatis:
  type-aliases-package: cn.itcast.userservice.pojo
  #配置 eureka的信息

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:   #多个注册中心url 可以使用逗号 隔开 ,http://127.0.0.1:10087/eureka
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-expiration-duration-in-seconds: 10 #过期时间 10s 开发环境配置 生产环境使用默认的
    lease-renewal-interval-in-seconds: 5 # 心跳周期 是5s 向注册中心发一次自己的注册
    instance-id: ${spring.application.name}:${server.port} #修改实例的id